Keianna edited portfolio
Nagle-Keianna/My_Portfolio pull request #2
Opened 2021-02-26 04:53 UTC by Nagle-Keianna

2021-02-26 12:21 UTC, mcshen-sps requested changes
Good work Keianna! I left some comments but they are all pretty minor. You're off to a great start!

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +      <p class= "font-stylings">LinkedIn: https://www.linkedin.com/in/keianna-nagle-57a6681a0/<br>GitHub: https://github.com/Nagle-Keianna</br>
Try to keep each line of code at fewer than 70 characters so readers don't have to scroll to see it all. This won't affect how the text renders on the actual webpage because HTML will reduce any whitespace, including new lines, to a single space.

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +      <p class= "font-stylings">LinkedIn: https://www.linkedin.com/in/keianna-nagle-57a6681a0/<br>GitHub: https://github.com/Nagle-Keianna</br>
`<br>` is a line break. There is no need to have a closing tag. `</br>` is just read as another line break. If that is the intent, change it to `<br>`

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +      <img src ="/home/knagle/software-product-sprint/portfolio/src/main/webapp/images/Grad-Headshot.PNG"/>
Whenever you have an image, it's good practice to include an `alt` attribute. e.g. `alt="graduation headshot"`

This is important for accessibility: the attribute will let a blind user know what the image is about. It also functions as placeholder text if the image can't be shown for any reason.

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/style.css
> +    left: 300px;
Keep declarations in alphabetical order ("left" before "position") for consistency and ease of maintenance

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/style.css
> +.font-stylings {
Add a new line before each rule for consistency

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/style.css
> +#page-background {
You can just use `body` here instead of `#page-background` and then you won't need the id attribute. Also since you seem to use the same text style throughout the body, you could include the declarations in `font-stylings` in this rule as well.

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +      <h1 class= "font-stylings">My Portfolio</h1>
remove the spaces between attribute and its value
```suggestion
      <h1 class="font-stylings">My Portfolio</h1>
```

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +      <p class= "font-stylings">LinkedIn: https://www.linkedin.com/in/keianna-nagle-57a6681a0/<br>GitHub: https://github.com/Nagle-Keianna</br>
Try using hyperlink elements for your links `<a href="URL">text</a>`

2021-02-26 12:21 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
> +      <p class= "font-stylings"> A hidden talent of mine is baking! I love baking for my friends and family and have made things like cookies, cinnamon sugar soft pretzels, cinnamon rolls, snickerdoo
```suggestion
      <p class= "font-stylings">A hidden talent of mine is baking! I love baking for my friends and family and have made things like cookies, cinnamon sugar soft pretzels, cinnamon rolls, snickerdoodle bars, and imitation King Hawaiian Rolls.</p>
```

2021-03-01 20:33 UTC, Nagle-Keianna commented
Thanks! Reviewed your recommendations and made some changes.

2021-03-01 21:30 UTC, mcshen-sps commented on portfolio/src/main/webapp/style.css
> +}
Since these declarations are in the body now, you don't really need the font-stylings class anymore

2021-03-01 21:30 UTC, mcshen-sps commented on portfolio/pom.xml
> +</googleCloudProjectId>
The closing tag should be on the same line or at the same indentation level as the opening tag

2021-03-01 21:30 UTC, mcshen-sps commented on portfolio/src/main/webapp/style.css
> +#body {
Unless you need to specifically access the body that you've given the id "body", you could instead omit the `id` attribute and just use `body` here (without the `#`) to apply the rule to all `<body>` elements

I'm okay with it either way, it's up to you

2021-03-01 21:43 UTC, mcshen-sps approved these changes
Great work! Keep it up!

2021-03-05 00:07 UTC, merged