Json walkthrough
Nagle-Keianna/My_Portfolio pull request #5
Opened 2021-03-06 23:06 UTC by Nagle-Keianna

2021-03-07 05:01 UTC, mcshen-sps requested changes
Good work Keianna! Requesting a few small changes before approval

2021-03-07 05:01 UTC, mcshen-sps commented on portfolio/src/main/webapp/fetch_script.js
>  async function showServerTime() {
This function name is kind of misleading

2021-03-07 05:01 UTC, mcshen-sps commented on portfolio/pom.xml
> +    <dependency>
To be consistent with the other dependencies, and so a reader understands the purpose of each dependency, add a new line and a comment saying what the dependency is for.

Also it looks like the jetty dependency is there twice for some reason, so you can delete one of them.

2021-03-07 05:01 UTC, mcshen-sps commented on portfolio/src/main/java/com/google/sps/servlets/SampleServlet.java
> +     */
This looks like a javadoc comment, but it's empty. Did you mean to fill it out or delete it?

2021-03-07 05:01 UTC, mcshen-sps commented on portfolio/src/main/webapp/index.html
>        <div id="greeting-container"></div>
The id `greeting-container` isn't really accurate anymore since it doesn't hold a greeting. You might want to change it to something more descriptive. Same for the `addRandomGreeting` function

2021-03-09 20:50 UTC, Nagle-Keianna commented on portfolio/pom.xml
> +    <dependency>
I think the jetty dependencies are different because when I deleted one of them I got import cannot be resolved errors on my servlet files. I think they are slightly different due to their artifact Id's.

2021-03-09 20:57 UTC, mcshen-sps commented on portfolio/pom.xml
> +    <dependency>
You're right, my mistake. Sorry for the confusion

2021-03-09 21:57 UTC, mcshen-sps approved these changes
Great work!

2021-03-09 22:57 UTC, merged